[package]
name = "py_monte_carlo"
version = "1.1.0"
authors = ["sumnernh@gmail.com <sumnernh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "py_monte_carlo"
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
itertools = "^0.9"
rand = "^0.7"
rand_chacha = "^0.2"
rayon = "^1.2"
num = "^0.2"
numpy = "^0.8"

[dependencies.ising_monte_carlo]
version = "^1.2"
git = "https://github.com/Renmusxd/IsingMonteCarlo"
features = ["autocorrelations", "parallel-tempering"]

[dependencies.pyo3]
version = "^0.9"
features = ["extension-module"]

[dependencies.ndarray]
version = "^0.13"
features = ["rayon"]
