[package]
name = "py_monte_carlo"
version = "1.3.2"
authors = ["Sumner Hearth <sumnernh@gmail.com>"]
edition = "2018"

[lib]
name = "py_monte_carlo"
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
itertools = "^0.9"
rand = "^0.7"
rayon = "^1.2"
numpy = "^0.8"

[dependencies.ising_monte_carlo]
version = "^1.3"
git = "https://github.com/Renmusxd/IsingMonteCarlo"
features = ["autocorrelations", "parallel-tempering"]

[dependencies.pyo3]
version = "^0.9"
features = ["extension-module"]

[dependencies.ndarray]
version = "^0.13"
features = ["rayon"]